### ISSUE TITLE
Tooltips don't show when using self.tooltipManager.showsBackdropView = YES;

### ISSUE THREAD

**Issue by LaChrome** [JoeFryer/JDFTooltips#6]
Hi,

I'm unable to get tooltips to show when using the line: "self.tooltipManager.showsBackdropView = YES;"

If I remove that line, then the tooltips appear, but without the backdrop, and they have to be individually pressed to dismiss them (instead of being able to tap anywhere on the screen).

The configuration is straight forward, as I copied the code from the example.

Possible issue with iOS9?

Thanks.

I've also found that the line:
[self.tooltipManager setDismissOnTouchForAllTooltips:NO];

doesn't change the behaviour of the tooltips at all (they still dismiss when touched).

Am I doing something obviously wrong?

Thanks.

Chris

**Comment by LaChrome** [comment]
For some reason (I haven't dug into why yet), but the line:
UIWindow *window = self.hostView.window;

Always returns NULL, so the backdrop doesn't show.

This happens when you initialize the JDFSequentialTooltipManager in the "ViewDidLoad" function of the view controller.

To fix the issue, I moved the JDFSequentialTooltipManager initialization into the "ViewDidAppear" function, which solved the issue. showBackdropView now works, and the line "UIWindow *window = self.hostView.window;" no longer returns null.

**Comment by JoeFryer** [comment]
Hi @Apptation,

Thanks for reporting this stuff. 

So:
- **Tooltips not appearing when shown from `viewDidLoad` with the backdrop enabled:** you're right, this doesn't work (because the view doesn't have a window at that point, as you pointed out). For the time being, I'll update the documentation to make this clear. In the long term, I'll look at removing the the use of the window.
- **`dismissOnTouchForAllTooltips` not working:** I've fixed this now :)

Thanks Again!
